# -*- coding: utf-8 -*-
"""zoo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XNOk6oN6OGxIVghx1fv6Ks7SqRDh8kyF
"""

def hours():
  return('Open 9-5 daily')